### ISSUE TITLE
Alternative instance is a lie

### ISSUE THREAD

**Issue by phadej** [emilypi/nonempty-vector#1]
NonEmptyVector cannot be `empty`.

Also GND `Read` instance probably accepts empty vector.

**Comment by phadej** [comment]
Also `Generic` instance breakage the abstraction layer.

**Comment by phadej** [comment]
Also `Generic` instance breakage the abstraction layer.

**Comment by emilypi** [comment]
Good spot - I'd forgotten about the `empty` constraint! You're right about `Read` too - apparently it's just calling `fromList` behind the scenes. 

I'm not good with `Generic` - is there anything we can do there?

**Comment by phadej** [comment]
With `Generic`, no, it’s just wrong. `toVector` / `fromVector` should be enough to implement instances. It’s not as handy as `DeriveAnyClass`, but there is an invariant one have to keep. Maybe having an `unsafeFromVector` which doesn’t wrap in Maybe would be good idea (two variants? One which does bound check and one which doesn’t. CF index and unsafeIndex)

**Comment by emilypi** [comment]
That makes sense, okay. I'll add an `unsafe` constructor.

**Comment by emilypi** [comment]
Thanks for the help @phadej - addressed and closing
