### ISSUE TITLE
A variant of fromNonEmptyN which doesn’t wrap result in Maybe

### ISSUE THREAD

**Issue by phadej** [emilypi/nonempty-vector#2]
I.e. return a NonEmptyVector with `max 1 n` first elements. That would be useful, as often (in vector) case we call `fromListN (length xs) xs` where the length is precalculated from some previous pass.

Similarly, maybe there should be variants for unfoldr which take first element, I.e `:: (b -> Maybe (a, b)) -> a -> b -> NonEmptyVector a`

**Comment by emilypi** [comment]
Good suggestions - Yeah, I'd like to incorporate more `NonEmptyVector`-specific constructions in addition to satisfying the parity with the `Vector` API. If you have any more, let's come up with a list of potential variants and either you or I could implement it. PR's very welcome with this.

**Comment by emilypi** [comment]
Thanks for the help @phadej - addressed and closing
