### ISSUE TITLE
GHC 9.12

### ISSUE THREAD

**Issue by andreasabel** [emilypi/nonempty-vector#22]
> [__1] rejecting: base-4.21.0.0/installed-d274 (conflict: nonempty-vector => base>=4.14 && <4.21)

Relaxing `base` seems to be sufficient:
> cabal install --ignore-project -w ghc-9.12.1 nonempty-vector --allow-newer=nonempty-vector:base

**Comment by emilypi** [comment]
On it. Looks like there are some code changes required to defeat some warnings though. I'll have a minor version release out when CI is green.

**Comment by emilypi** [comment]
https://hackage.haskell.org/package/nonempty-vector-0.2.4 is now up. Please confirm that it works for you and we'll close this

**Comment by andreasabel** [comment]
Thanks for the swift action!
Yes, building the package works now with GHC 9.12.
