### ISSUE TITLE
A way to build from an A and a Vector

### ISSUE THREAD

**Issue by AlistairB** [emilypi/nonempty-vector#7]
Hi,

Would it make sense to add some equivalent of `:|` for `NonEmpty` but for `NonEmptyVector`? I suppose in this case it would need to be a function, not a data constructor. ie. something like `consV :: a -> Vector a -> NonEmptyVector a`.

I suppose an equivalent `snocV` might also be useful.

I'd be happy to open a PR if this is all desirable.

**Comment by emilypi** [comment]
Seems like a pretty unoffensive thing to ask for! I'd accept a PR for it 😄
